-- Marks chores auto-generated by the meal-plan/laundry daily jobs, so maintenance can purge
-- them once resolved without touching chores a parent created by hand.
ALTER TABLE "Chore" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
