import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { seedDemoFamily } from '../../prisma/seed.js';
import { createTestDb, type TestDb } from '../test-utils/testDb.js';
import { createMaintenanceService, type MaintenanceService } from './maintenanceService.js';

describe('maintenanceService (seeded demo family)', () => {
  let db: TestDb;
  let service: MaintenanceService;
  let elodieAccountId: string;

  beforeAll(async () => {
    db = createTestDb();
    await seedDemoFamily(db.prisma);
    service = createMaintenanceService(db.prisma);

    const elodie = await db.prisma.user.findUniqueOrThrow({
      where: { id: 'demo-elodie' },
      include: { childAccount: true },
    });
    elodieAccountId = elodie.childAccount!.id;
  });

  afterAll(() => db.teardown());

  it('purges notification-send logs older than 30 days, but keeps recent ones', async () => {
    const old = new Date(Date.now() - 40 * 24 * 60 * 60 * 1000);
    const recent = new Date();

    await db.prisma.mealCookNotificationLog.createMany({
      data: [
        { familyId: 'demo-family', date: old, kind: 'TODAY', userId: 'demo-elodie', createdAt: old },
        { familyId: 'demo-family', date: recent, kind: 'TODAY', userId: 'demo-matthieu', createdAt: recent },
      ],
    });
    const customNotification = await db.prisma.customNotification.create({
      data: { familyId: 'demo-family', title: 'Test', body: 'Test', date: recent, createdById: 'demo-papa' },
    });
    await db.prisma.customNotificationLog.createMany({
      data: [
        { customNotificationId: customNotification.id, date: old, createdAt: old },
      ],
    });

    const result = await service.purgeOldNotificationLogs();
    expect(result.meal).toBe(1);
    expect(result.custom).toBe(1);

    expect(await db.prisma.mealCookNotificationLog.count()).toBe(1);
    const [remaining] = await db.prisma.mealCookNotificationLog.findMany();
    expect(remaining!.userId).toBe('demo-matthieu');
    expect(await db.prisma.customNotificationLog.count()).toBe(0);
  });

  it('purges resolved chore completions and done one-off personal tasks from past days, keeping today\'s and any still-pending one', async () => {
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const today = new Date();

    const chore = await db.prisma.chore.create({
      data: {
        familyId: 'demo-family',
        childUserId: 'demo-elodie',
        title: 'Test chore',
        rewardType: 'POINTS',
        rewardPoints: 5,
        recurrence: 'DAILY',
      },
    });
    await db.prisma.choreCompletion.createMany({
      data: [
        { choreId: chore.id, periodStart: yesterday, status: 'APPROVED', rewardType: 'POINTS', rewardPoints: 5 },
        { choreId: chore.id, periodStart: yesterday, status: 'PENDING', rewardType: 'POINTS', rewardPoints: 5 },
        { choreId: chore.id, periodStart: today, status: 'APPROVED', rewardType: 'POINTS', rewardPoints: 5 },
      ],
    });

    await db.prisma.personalTask.createMany({
      data: [
        { familyId: 'demo-family', userId: 'demo-elodie', title: 'Old done', recurring: false, date: yesterday, done: true },
        { familyId: 'demo-family', userId: 'demo-elodie', title: 'Old not done', recurring: false, date: yesterday, done: false },
        { familyId: 'demo-family', userId: 'demo-elodie', title: 'Today done', recurring: false, date: today, done: true },
      ],
    });

    const result = await service.purgeOldCompletedTasks();
    expect(result.choreCompletions).toBe(1);
    expect(result.personalTasks).toBe(1);

    const remainingCompletions = await db.prisma.choreCompletion.findMany({ where: { choreId: chore.id } });
    expect(remainingCompletions).toHaveLength(2);
    expect(remainingCompletions.map((c) => c.status).sort()).toEqual(['APPROVED', 'PENDING']);

    const remainingTasks = await db.prisma.personalTask.findMany({ where: { userId: 'demo-elodie' } });
    expect(remainingTasks.map((t) => t.title).sort()).toEqual(['Old not done', 'Today done']);
  });

  it('deletes resolved auto-generated chores (meal/laundry) from past days, but keeps unresolved, today\'s, and manually-created ones', async () => {
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const today = new Date();

    const resolvedYesterday = await db.prisma.chore.create({
      data: {
        familyId: 'demo-family',
        childUserId: 'demo-elodie',
        title: 'Ménage : Linge foncé',
        rewardType: 'POINTS',
        rewardPoints: 5,
        recurrence: 'ONCE',
        autoGenerated: true,
        active: false,
        createdAt: yesterday,
      },
    });
    const resolvedToday = await db.prisma.chore.create({
      data: {
        familyId: 'demo-family',
        childUserId: 'demo-elodie',
        title: 'Préparer le repas du soir',
        rewardType: 'POINTS',
        rewardPoints: 5,
        recurrence: 'ONCE',
        autoGenerated: true,
        active: false,
        createdAt: today,
      },
    });
    const stillActiveYesterday = await db.prisma.chore.create({
      data: {
        familyId: 'demo-family',
        childUserId: 'demo-elodie',
        title: 'Ménage : Blancs',
        rewardType: 'POINTS',
        rewardPoints: 5,
        recurrence: 'ONCE',
        autoGenerated: true,
        active: true,
        createdAt: yesterday,
      },
    });
    const manuallyCreatedResolved = await db.prisma.chore.create({
      data: {
        familyId: 'demo-family',
        childUserId: 'demo-elodie',
        title: 'Aider à repeindre la clôture',
        rewardType: 'POINTS',
        rewardPoints: 20,
        recurrence: 'ONCE',
        autoGenerated: false,
        active: false,
        createdAt: yesterday,
      },
    });
    await db.prisma.choreCompletion.create({
      data: { choreId: resolvedYesterday.id, periodStart: yesterday, status: 'APPROVED', rewardType: 'POINTS', rewardPoints: 5 },
    });

    const count = await service.purgeResolvedAutoGeneratedChores();
    expect(count).toBe(1);

    const remainingIds = (
      await db.prisma.chore.findMany({
        where: { id: { in: [resolvedYesterday.id, resolvedToday.id, stillActiveYesterday.id, manuallyCreatedResolved.id] } },
      })
    ).map((c) => c.id);
    expect(remainingIds.sort()).toEqual([resolvedToday.id, stillActiveYesterday.id, manuallyCreatedResolved.id].sort());

    expect(await db.prisma.choreCompletion.count({ where: { choreId: resolvedYesterday.id } })).toBe(0);
  });

  it('purges past occurrence-status overlays once both their date and any postponed-to date have passed', async () => {
    const twoDaysAgo = new Date(Date.now() - 2 * 24 * 60 * 60 * 1000);
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const today = new Date();
    const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000);

    const laundryType = await db.prisma.laundryType.create({
      data: { familyId: 'demo-family', name: 'Test purge', scheduleType: 'WEEKLY', weekdays: [0] },
    });

    await db.prisma.mealPlanOccurrenceStatus.createMany({
      data: [
        { familyId: 'demo-family', date: twoDaysAgo, done: true },
        { familyId: 'demo-family', date: yesterday, postponedToDate: tomorrow },
        { familyId: 'demo-family', date: today, done: true },
      ],
    });
    await db.prisma.laundryOccurrenceStatus.createMany({
      data: [{ familyId: 'demo-family', laundryTypeId: laundryType.id, date: yesterday, done: true }],
    });

    const result = await service.purgeOldOccurrenceStatuses();
    expect(result.mealPlan).toBe(1);
    expect(result.laundry).toBe(1);

    const remainingMealPlan = await db.prisma.mealPlanOccurrenceStatus.findMany({ where: { familyId: 'demo-family' } });
    expect(remainingMealPlan).toHaveLength(2);
    expect(remainingMealPlan.some((r) => r.postponedToDate !== null)).toBe(true);
    expect(remainingMealPlan.some((r) => r.date.getTime() === today.getTime())).toBe(true);
    expect(await db.prisma.laundryOccurrenceStatus.count({ where: { laundryTypeId: laundryType.id } })).toBe(0);
  });

  it('purges expired or revoked refresh sessions, but keeps active ones', async () => {
    await db.prisma.refreshSession.createMany({
      data: [
        {
          userId: 'demo-elodie',
          tokenHash: 'expired-hash',
          expiresAt: new Date(Date.now() - 60_000),
        },
        {
          userId: 'demo-elodie',
          tokenHash: 'revoked-hash',
          expiresAt: new Date(Date.now() + 60_000),
          revokedAt: new Date(),
        },
        {
          userId: 'demo-elodie',
          tokenHash: 'active-hash',
          expiresAt: new Date(Date.now() + 60_000),
        },
      ],
    });

    const count = await service.purgeStaleRefreshSessions();
    expect(count).toBe(2);

    const remaining = await db.prisma.refreshSession.findMany({ where: { userId: 'demo-elodie' } });
    expect(remaining.map((r) => r.tokenHash)).toEqual(['active-hash']);
  });

  it('purges resolved stock orders from past days, but keeps pending and today\'s', async () => {
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);

    const baseOrder = {
      requesterId: 'demo-elodie',
      accountId: elodieAccountId,
      type: 'BUY' as const,
      symbol: 'AAPL',
      companyName: 'Apple',
      quantity: 1,
      estimatedPriceCents: 10_000,
    };

    const resolvedYesterday = await db.prisma.stockOrder.create({
      data: { ...baseOrder, status: 'APPROVED', updatedAt: yesterday },
    });
    const resolvedToday = await db.prisma.stockOrder.create({
      data: { ...baseOrder, status: 'REJECTED' },
    });
    const stillPending = await db.prisma.stockOrder.create({
      data: { ...baseOrder, status: 'PENDING', updatedAt: yesterday },
    });

    const count = await service.purgeResolvedStockOrders();
    expect(count).toBe(1);

    const remainingIds = (
      await db.prisma.stockOrder.findMany({
        where: { id: { in: [resolvedYesterday.id, resolvedToday.id, stillPending.id] } },
      })
    ).map((o) => o.id);
    expect(remainingIds.sort()).toEqual([resolvedToday.id, stillPending.id].sort());
  });
});
