import type { PrismaClient } from '@prisma/client';
import { getStartOfDay } from '../utils/dateWeek.js';

const RETENTION_DAYS = 30;

export function createMaintenanceService(prisma: PrismaClient) {
  return {
    /// These three tables are pure same-day "already sent this reminder" idempotency markers
    /// (each has a unique constraint keyed on today's date) — once a day has passed, its rows
    /// never need to be checked again, so they're safe to purge after a wide safety margin.
    /// Unlike InterestHistory/AllowanceHistory, which must be kept forever: those guard against
    /// double-crediting money on a much longer (month/week-since-eligibility) lookback window.
    async purgeOldNotificationLogs(): Promise<{ meal: number; laundry: number; custom: number }> {
      const cutoff = new Date(Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000);

      const [meal, laundry, custom] = await Promise.all([
        prisma.mealCookNotificationLog.deleteMany({ where: { createdAt: { lt: cutoff } } }),
        prisma.laundryNotificationLog.deleteMany({ where: { createdAt: { lt: cutoff } } }),
        prisma.customNotificationLog.deleteMany({ where: { createdAt: { lt: cutoff } } }),
      ]);

      return { meal: meal.count, laundry: laundry.count, custom: custom.count };
    },

    /// A chore's own current-period status only ever looks at *this* period's completion (see
    /// choreCompletionRepository.findLatestForPeriod) — nothing reads a resolved completion once
    /// its period has passed, so once yesterday-or-earlier and no longer PENDING (a parent might
    /// still need to act on a PENDING one, however old), it's pure clutter. Same reasoning for a
    /// one-off personal task once done and its date has passed — a recurring one never
    /// accumulates rows (its `done` state lives on the single row via `lastDoneDate`), so it's
    /// untouched here.
    async purgeOldCompletedTasks(): Promise<{ choreCompletions: number; personalTasks: number }> {
      const startOfToday = getStartOfDay(new Date());

      const [choreCompletions, personalTasks] = await Promise.all([
        prisma.choreCompletion.deleteMany({
          where: { periodStart: { lt: startOfToday }, status: { in: ['APPROVED', 'REJECTED'] } },
        }),
        prisma.personalTask.deleteMany({
          where: { recurring: false, done: true, date: { lt: startOfToday } },
        }),
      ]);

      return { choreCompletions: choreCompletions.count, personalTasks: personalTasks.count };
    },

    /// Meal-plan/laundry generate one real, actionable `Chore` per assignee per day
    /// (autoGenerated: true) — a fresh calendar-driven duplicate, not something a parent
    /// tracks history for the way they might a chore they created themselves. Once resolved
    /// (a ONCE chore going inactive) and no longer today's, it's pure clutter — hard-deleted,
    /// cascading its completion, unlike a real chore which is never hard-deleted.
    async purgeResolvedAutoGeneratedChores(): Promise<number> {
      const startOfToday = getStartOfDay(new Date());
      const { count } = await prisma.chore.deleteMany({
        where: { autoGenerated: true, active: false, createdAt: { lt: startOfToday } },
      });
      return count;
    },

    /// Both are pure display overlays on top of a calendar-driven rotation (see their own
    /// model comments) — only ever read within an "upcoming" window that never looks at the
    /// past. A row's origin `date` passing isn't enough on its own though: a postponed-from
    /// row keeps `postponedToDate` pointing at a still-future date that a range query still
    /// needs to find, so it's only safe once *both* dates (or there is no postponement) have
    /// passed.
    async purgeOldOccurrenceStatuses(): Promise<{ mealPlan: number; laundry: number }> {
      const startOfToday = getStartOfDay(new Date());
      const where = {
        date: { lt: startOfToday },
        OR: [{ postponedToDate: null }, { postponedToDate: { lt: startOfToday } }],
      };

      const [mealPlan, laundry] = await Promise.all([
        prisma.mealPlanOccurrenceStatus.deleteMany({ where }),
        prisma.laundryOccurrenceStatus.deleteMany({ where }),
      ]);

      return { mealPlan: mealPlan.count, laundry: laundry.count };
    },

    /// A refresh session is only ever looked up filtered to `revokedAt: null` and a future
    /// `expiresAt` (see refreshSessionRepository) — once either is no longer true, nothing
    /// reads the row again.
    async purgeStaleRefreshSessions(): Promise<number> {
      const { count } = await prisma.refreshSession.deleteMany({
        where: { OR: [{ revokedAt: { not: null } }, { expiresAt: { lt: new Date() } }] },
      });
      return count;
    },

    /// A resolved stock order (APPROVED/REJECTED) is never shown anywhere — the frontend only
    /// ever renders PENDING ones (StockPortfolioView filters to `status === 'PENDING'`). Once
    /// approved, the trade itself lives on as a real Transaction, so nothing is lost by
    /// dropping the request record. PENDING orders are always kept — a parent still needs to
    /// see and act on them, however old.
    async purgeResolvedStockOrders(): Promise<number> {
      const startOfToday = getStartOfDay(new Date());
      const { count } = await prisma.stockOrder.deleteMany({
        where: { status: { in: ['APPROVED', 'REJECTED'] }, updatedAt: { lt: startOfToday } },
      });
      return count;
    },
  };
}

export type MaintenanceService = ReturnType<typeof createMaintenanceService>;
